# -*- coding: utf-8 -*-
"""Project: 6  Countdown Timer Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a4mofKpgEkP-Q0gy0RWRH0yp8xV6ANG
"""

import time
from IPython.display import clear_output

def countdown_timer(seconds):
  while seconds >= 0:
    mins = seconds // 60
    secs = seconds % 60
    clear_output(wait=True)
    print(f"Time's left.{mins:02}:{secs:02}")
    time.sleep(1)
    seconds -= 1

print("Time's up!")

seconds = int(input("Enter time in seconds:"))
countdown_timer(seconds)